-- ============================================================================
-- PROYECTO FINAL — BASES DE DATOS II
-- QuindioFlix — Plataforma de Streaming de Contenido Multimedia
-- Universidad del Quindío — 2026-1
-- ----------------------------------------------------------------------------
-- Script:   03_QuindioFlix_DatosPrueba_v2.sql
-- Versión:  2.0 — Corregido para Oracle XE 21c + SQL Developer
-- Cambios:  OVERRIDING SYSTEM VALUE eliminado → se usa ALTER BY DEFAULT
--           ORDER BY tabla → ORDER BY 1
--           CALIFICACIONES query → GROUP BY para evitar duplicados
-- ============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;

-- ============================================================================
-- SECCIÓN 0-A: LIMPIEZA DE DATOS ANTERIORES (si el script se ejecutó antes)
-- ============================================================================
-- Romper referencias circulares primero
UPDATE USUARIOS    SET id_referidor    = NULL WHERE id_referidor    IS NOT NULL;
UPDATE DEPARTAMENTOS SET id_jefe_empleado = NULL WHERE id_jefe_empleado IS NOT NULL;
COMMIT;

-- Eliminar en orden inverso de dependencias
DELETE FROM REPORTES;
DELETE FROM PAGOS;
DELETE FROM FAVORITOS;
DELETE FROM CALIFICACIONES;
DELETE FROM REPRODUCCIONES;
DELETE FROM EPISODIOS;
DELETE FROM TEMPORADAS;
DELETE FROM CONTENIDO_RELACIONADO;
DELETE FROM CONTENIDO_GENERO;
DELETE FROM PERFILES;
DELETE FROM CONTENIDO;
DELETE FROM USUARIOS;
DELETE FROM EMPLEADOS;
DELETE FROM DEPARTAMENTOS;
DELETE FROM GENEROS;
DELETE FROM CATEGORIAS;
DELETE FROM PLANES;
COMMIT;
DBMS_OUTPUT.PUT_LINE('Limpieza completada.');

-- ============================================================================
-- SECCIÓN 0-B: CAMBIAR IDENTITY A "BY DEFAULT"
-- ============================================================================
-- FIX PRINCIPAL: GENERATED ALWAYS no permite insertar valores explícitos.
-- Cambiamos a BY DEFAULT para poder especificar IDs y referenciarlos en FKs.
-- Al final del script se restablece con START WITH LIMIT VALUE.
-- ============================================================================
ALTER TABLE PLANES         MODIFY id_plan          GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE CATEGORIAS     MODIFY id_categoria     GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE GENEROS        MODIFY id_genero        GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE DEPARTAMENTOS  MODIFY id_departamento  GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE EMPLEADOS      MODIFY id_empleado      GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE USUARIOS       MODIFY id_usuario       GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE PERFILES       MODIFY id_perfil        GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE CONTENIDO      MODIFY id_contenido     GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE TEMPORADAS     MODIFY id_temporada     GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE EPISODIOS      MODIFY id_episodio      GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE PAGOS          MODIFY id_pago          GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE REPRODUCCIONES MODIFY id_reproduccion  GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE CALIFICACIONES MODIFY id_calificacion  GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE REPORTES       MODIFY id_reporte       GENERATED BY DEFAULT AS IDENTITY;
DBMS_OUTPUT.PUT_LINE('Columnas IDENTITY ajustadas a BY DEFAULT.');

-- ============================================================================
-- SECCIÓN 1: TABLAS BASE SIN DEPENDENCIAS
-- ============================================================================

-- PLANES (3 registros)
INSERT INTO PLANES VALUES (1,'Básico',14900,1,'SD',2);
INSERT INTO PLANES VALUES (2,'Estándar',24900,2,'HD',3);
INSERT INTO PLANES VALUES (3,'Premium',34900,4,'4K',5);

-- CATEGORIAS (5 registros)
INSERT INTO CATEGORIAS VALUES (1,'Película','Largometrajes de ficción, animación y cine');
INSERT INTO CATEGORIAS VALUES (2,'Serie','Contenido serializado organizado en temporadas y episodios');
INSERT INTO CATEGORIAS VALUES (3,'Documental','Contenido no ficción, reportajes y periodismo visual');
INSERT INTO CATEGORIAS VALUES (4,'Música','Conciertos, videos musicales y álbumes visuales');
INSERT INTO CATEGORIAS VALUES (5,'Podcast','Programas de audio y conversación por temporadas');

-- GENEROS (10 registros)
INSERT INTO GENEROS VALUES (1,'Acción');
INSERT INTO GENEROS VALUES (2,'Comedia');
INSERT INTO GENEROS VALUES (3,'Drama');
INSERT INTO GENEROS VALUES (4,'Suspenso');
INSERT INTO GENEROS VALUES (5,'Romance');
INSERT INTO GENEROS VALUES (6,'Ciencia Ficción');
INSERT INTO GENEROS VALUES (7,'Terror');
INSERT INTO GENEROS VALUES (8,'Infantil');
INSERT INTO GENEROS VALUES (9,'Musical');
INSERT INTO GENEROS VALUES (10,'Thriller');

-- DEPARTAMENTOS (5 registros — sin jefe por FK circular, se actualiza después)
INSERT INTO DEPARTAMENTOS VALUES (1,'Tecnología',NULL);
INSERT INTO DEPARTAMENTOS VALUES (2,'Contenido',NULL);
INSERT INTO DEPARTAMENTOS VALUES (3,'Marketing',NULL);
INSERT INTO DEPARTAMENTOS VALUES (4,'Soporte',NULL);
INSERT INTO DEPARTAMENTOS VALUES (5,'Finanzas',NULL);

COMMIT;
DBMS_OUTPUT.PUT_LINE('Sección 1 completada: Planes, Categorias, Generos, Departamentos.');

-- ============================================================================
-- SECCIÓN 2: EMPLEADOS Y JERARQUÍA
-- ============================================================================
-- Dept 1 Tecnología  : emp 1(jefe), 2, 3
-- Dept 2 Contenido   : emp 4(jefe), 5, 6, 7, 8  ← responsables del catálogo
-- Dept 3 Marketing   : emp 9(jefe), 10, 11
-- Dept 4 Soporte     : emp 12(jefe), 13, 14       ← gestionan reportes
-- Dept 5 Finanzas    : emp 15(jefe)

INSERT INTO EMPLEADOS VALUES (1,'Carlos Rodríguez','c.rodriguez@quindioflix.co','Director de Tecnología',DATE '2020-03-15',1,NULL);
INSERT INTO EMPLEADOS VALUES (2,'Ana Martínez','a.martinez@quindioflix.co','Desarrollador Senior',DATE '2021-01-10',1,1);
INSERT INTO EMPLEADOS VALUES (3,'Luis Gómez','l.gomez@quindioflix.co','DBA Oracle',DATE '2021-06-01',1,1);
INSERT INTO EMPLEADOS VALUES (4,'María López','m.lopez@quindioflix.co','Directora de Contenido',DATE '2020-05-20',2,NULL);
INSERT INTO EMPLEADOS VALUES (5,'Andrés Pérez','a.perez@quindioflix.co','Gestor de Catálogo Sr.',DATE '2021-03-15',2,4);
INSERT INTO EMPLEADOS VALUES (6,'Sofía Torres','s.torres@quindioflix.co','Editora de Contenido',DATE '2022-01-10',2,4);
INSERT INTO EMPLEADOS VALUES (7,'Diego Vargas','d.vargas@quindioflix.co','Gestor de Contenido',DATE '2022-07-01',2,5);
INSERT INTO EMPLEADOS VALUES (8,'Valentina Cruz','v.cruz@quindioflix.co','Analista de Contenido',DATE '2023-02-01',2,5);
INSERT INTO EMPLEADOS VALUES (9,'Ricardo Herrera','r.herrera@quindioflix.co','Director de Marketing',DATE '2020-08-01',3,NULL);
INSERT INTO EMPLEADOS VALUES (10,'Paola Jiménez','p.jimenez@quindioflix.co','Community Manager',DATE '2022-04-01',3,9);
INSERT INTO EMPLEADOS VALUES (11,'Felipe Moreno','f.moreno@quindioflix.co','Analista de Marketing',DATE '2023-01-15',3,9);
INSERT INTO EMPLEADOS VALUES (12,'Gloria Sánchez','g.sanchez@quindioflix.co','Jefe de Soporte',DATE '2020-11-01',4,NULL);
INSERT INTO EMPLEADOS VALUES (13,'Juan Castillo','j.castillo@quindioflix.co','Agente de Soporte Sr.',DATE '2021-09-01',4,12);
INSERT INTO EMPLEADOS VALUES (14,'Camila Reyes','c.reyes@quindioflix.co','Agente de Soporte',DATE '2022-11-01',4,12);
INSERT INTO EMPLEADOS VALUES (15,'Hernán Díaz','h.diaz@quindioflix.co','Director Financiero',DATE '2020-01-15',5,NULL);

-- Asignar jefes a cada departamento (resuelve FK circular DEPARTAMENTOS↔EMPLEADOS)
UPDATE DEPARTAMENTOS SET id_jefe_empleado = 1  WHERE id_departamento = 1;
UPDATE DEPARTAMENTOS SET id_jefe_empleado = 4  WHERE id_departamento = 2;
UPDATE DEPARTAMENTOS SET id_jefe_empleado = 9  WHERE id_departamento = 3;
UPDATE DEPARTAMENTOS SET id_jefe_empleado = 12 WHERE id_departamento = 4;
UPDATE DEPARTAMENTOS SET id_jefe_empleado = 15 WHERE id_departamento = 5;

COMMIT;
DBMS_OUTPUT.PUT_LINE('Sección 2 completada: Empleados y jerarquía.');

-- ============================================================================
-- SECCIÓN 3: USUARIOS (30 registros — 4 ciudades, 3 planes, ASIMÉTRICO)
-- ============================================================================
-- Distribución: Bogotá 10 | Medellín 10 | Cali 7 | Armenia 3
-- Moderadores (es_moderador='S'): usuarios 5, 15, 25
-- INACTIVOS (mora >30 días): usuarios 3, 13, 22
-- Referidos: 2→1, 6→5, 9→8, 12→11, 16→15, 19→18, 23→21, 26→25, 29→28
-- Columnas: id_usuario, nombre, email, telefono, fecha_nac, ciudad,
--           fecha_registro, estado_cuenta, fecha_ultimo_pago, id_plan,
--           id_referidor, es_moderador

-- BOGOTÁ — Plan Básico (4 usuarios)
INSERT INTO USUARIOS VALUES (1,'Juliana Ospina','juliana.ospina@gmail.com','3101234001',DATE '1990-05-15','Bogotá',DATE '2024-01-10','ACTIVO',DATE '2026-04-10',1,NULL,'N');
INSERT INTO USUARIOS VALUES (2,'Miguel Ángel Roa','miguel.roa@gmail.com','3101234002',DATE '1985-11-20','Bogotá',DATE '2024-02-15','ACTIVO',DATE '2026-04-15',1,1,'N');
INSERT INTO USUARIOS VALUES (3,'Fernanda Niño','fernanda.nino@hotmail.com','3101234003',DATE '1995-07-08','Bogotá',DATE '2024-03-01','INACTIVO',DATE '2026-02-01',1,NULL,'N');
INSERT INTO USUARIOS VALUES (4,'Sebastián Luna','sebastian.luna@gmail.com','3101234004',DATE '1988-02-28','Bogotá',DATE '2024-04-20','ACTIVO',DATE '2026-04-20',1,NULL,'N');

-- BOGOTÁ — Plan Estándar (3 usuarios)
INSERT INTO USUARIOS VALUES (5,'Laura Becerra','laura.becerra@gmail.com','3201234005',DATE '1992-09-12','Bogotá',DATE '2023-11-05','ACTIVO',DATE '2026-04-05',2,NULL,'S');
INSERT INTO USUARIOS VALUES (6,'Andrés Castaño','andres.castano@outlook.com','3201234006',DATE '1987-04-25','Bogotá',DATE '2024-01-18','ACTIVO',DATE '2026-04-18',2,5,'N');
INSERT INTO USUARIOS VALUES (7,'Natalia Forero','natalia.forero@gmail.com','3201234007',DATE '1993-12-03','Bogotá',DATE '2024-03-10','ACTIVO',DATE '2026-04-10',2,NULL,'N');

-- BOGOTÁ — Plan Premium (3 usuarios)
INSERT INTO USUARIOS VALUES (8,'Daniel Cardona','daniel.cardona@gmail.com','3301234008',DATE '1983-06-17','Bogotá',DATE '2023-09-01','ACTIVO',DATE '2026-04-01',3,NULL,'N');
INSERT INTO USUARIOS VALUES (9,'Carolina Suárez','carolina.suarez@gmail.com','3301234009',DATE '1991-01-30','Bogotá',DATE '2023-10-15','ACTIVO',DATE '2026-04-15',3,8,'N');
INSERT INTO USUARIOS VALUES (10,'Esteban Prada','esteban.prada@hotmail.com','3301234010',DATE '1989-08-22','Bogotá',DATE '2024-02-01','ACTIVO',DATE '2026-04-01',3,NULL,'N');

-- MEDELLÍN — Plan Básico (3 usuarios)
INSERT INTO USUARIOS VALUES (11,'Mariana Vélez','mariana.velez@gmail.com','3041234011',DATE '1994-03-14','Medellín',DATE '2024-01-20','ACTIVO',DATE '2026-04-20',1,NULL,'N');
INSERT INTO USUARIOS VALUES (12,'Camilo Arango','camilo.arango@gmail.com','3041234012',DATE '1990-10-05','Medellín',DATE '2024-02-28','ACTIVO',DATE '2026-04-28',1,11,'N');
INSERT INTO USUARIOS VALUES (13,'Tatiana Mesa','tatiana.mesa@hotmail.com','3041234013',DATE '1997-06-19','Medellín',DATE '2024-04-01','INACTIVO',DATE '2026-02-15',1,NULL,'N');

-- MEDELLÍN — Plan Estándar (4 usuarios)
INSERT INTO USUARIOS VALUES (14,'Tomás Ochoa','tomas.ochoa@gmail.com','3141234014',DATE '1986-12-08','Medellín',DATE '2023-08-15','ACTIVO',DATE '2026-04-15',2,NULL,'N');
INSERT INTO USUARIOS VALUES (15,'Isabella Ríos','isabella.rios@gmail.com','3141234015',DATE '1992-05-27','Medellín',DATE '2023-07-01','ACTIVO',DATE '2026-04-01',2,NULL,'S');
INSERT INTO USUARIOS VALUES (16,'Mauricio Palacio','mauricio.palacio@outlook.com','3141234016',DATE '1988-09-11','Medellín',DATE '2024-01-05','ACTIVO',DATE '2026-04-05',2,15,'N');
INSERT INTO USUARIOS VALUES (17,'Alejandra Gil','alejandra.gil@gmail.com','3141234017',DATE '1995-02-16','Medellín',DATE '2024-03-20','ACTIVO',DATE '2026-04-20',2,NULL,'N');

-- MEDELLÍN — Plan Premium (3 usuarios)
INSERT INTO USUARIOS VALUES (18,'Santiago Uribe','santiago.uribe@gmail.com','3241234018',DATE '1984-07-04','Medellín',DATE '2023-06-01','ACTIVO',DATE '2026-04-01',3,NULL,'N');
INSERT INTO USUARIOS VALUES (19,'Valentina Agudelo','valentina.agudelo@gmail.com','3241234019',DATE '1991-11-13','Medellín',DATE '2023-09-20','ACTIVO',DATE '2026-04-20',3,18,'N');
INSERT INTO USUARIOS VALUES (20,'Rodrigo Montoya','rodrigo.montoya@hotmail.com','3241234020',DATE '1987-04-02','Medellín',DATE '2024-01-10','ACTIVO',DATE '2026-04-10',3,NULL,'N');

-- CALI — Plan Básico (2 usuarios)
INSERT INTO USUARIOS VALUES (21,'Luisa Córdoba','luisa.cordoba@gmail.com','3181234021',DATE '1996-08-30','Cali',DATE '2024-02-10','ACTIVO',DATE '2026-04-10',1,NULL,'N');
INSERT INTO USUARIOS VALUES (22,'Jorge Lozano','jorge.lozano@hotmail.com','3181234022',DATE '1989-01-07','Cali',DATE '2024-03-05','INACTIVO',DATE '2026-02-05',1,NULL,'N');

-- CALI — Plan Estándar (2 usuarios)
INSERT INTO USUARIOS VALUES (23,'Gabriela Mosquera','gabriela.mosquera@gmail.com','3154321023',DATE '1993-06-22','Cali',DATE '2023-12-01','ACTIVO',DATE '2026-04-01',2,21,'N');
INSERT INTO USUARIOS VALUES (24,'Hernán Mina','hernan.mina@gmail.com','3154321024',DATE '1985-03-19','Cali',DATE '2024-01-25','ACTIVO',DATE '2026-04-25',2,NULL,'N');

-- CALI — Plan Premium (3 usuarios)
INSERT INTO USUARIOS VALUES (25,'Lorena Valencia','lorena.valencia@gmail.com','3174321025',DATE '1990-09-08','Cali',DATE '2023-05-15','ACTIVO',DATE '2026-04-15',3,NULL,'S');
INSERT INTO USUARIOS VALUES (26,'Mario Hurtado','mario.hurtado@gmail.com','3174321026',DATE '1982-12-25','Cali',DATE '2023-11-10','ACTIVO',DATE '2026-04-10',3,25,'N');
INSERT INTO USUARIOS VALUES (27,'Paula Caicedo','paula.caicedo@outlook.com','3174321027',DATE '1994-04-14','Cali',DATE '2024-02-20','ACTIVO',DATE '2026-04-20',3,NULL,'N');

-- ARMENIA — 3 usuarios (1 por plan)
INSERT INTO USUARIOS VALUES (28,'Estela Patiño','estela.patino@gmail.com','3006781028',DATE '1991-07-17','Armenia',DATE '2024-04-01','ACTIVO',DATE '2026-04-01',1,NULL,'N');
INSERT INTO USUARIOS VALUES (29,'Nicolás Londoño','nicolas.londono@gmail.com','3126781029',DATE '1988-02-11','Armenia',DATE '2024-03-15','ACTIVO',DATE '2026-04-15',2,28,'N');
INSERT INTO USUARIOS VALUES (30,'Andrea Salazar','andrea.salazar@gmail.com','3226781030',DATE '1986-10-28','Armenia',DATE '2023-12-20','ACTIVO',DATE '2026-04-20',3,NULL,'N');

COMMIT;
DBMS_OUTPUT.PUT_LINE('Sección 3 completada: 30 usuarios en 4 ciudades.');

-- ============================================================================
-- SECCIÓN 4: PERFILES (55 registros)
-- ============================================================================
-- Básico: máx 2 | Estándar: máx 3 | Premium: máx 5
-- Columnas: id_perfil, id_usuario, nombre_perfil, avatar, tipo_perfil, fecha_creacion

-- Bogotá
INSERT INTO PERFILES VALUES (1,1,'Juliana','av_01.png','adulto',DATE '2024-01-10');
INSERT INTO PERFILES VALUES (2,1,'Peques','av_kids01.png','infantil',DATE '2024-01-10');
INSERT INTO PERFILES VALUES (3,2,'Miguel','av_02.png','adulto',DATE '2024-02-15');
INSERT INTO PERFILES VALUES (4,3,'Fernanda','av_03.png','adulto',DATE '2024-03-01');
INSERT INTO PERFILES VALUES (5,3,'Bebés','av_kids02.png','infantil',DATE '2024-03-01');
INSERT INTO PERFILES VALUES (6,4,'Sebastián','av_04.png','adulto',DATE '2024-04-20');
INSERT INTO PERFILES VALUES (7,4,'Juanito','av_kids03.png','infantil',DATE '2024-04-20');
INSERT INTO PERFILES VALUES (8,5,'Laura','av_05.png','adulto',DATE '2023-11-05');
INSERT INTO PERFILES VALUES (9,5,'Acción','av_06.png','adulto',DATE '2023-11-05');
INSERT INTO PERFILES VALUES (10,5,'Infantil','av_kids04.png','infantil',DATE '2024-01-01');
INSERT INTO PERFILES VALUES (11,6,'Andrés','av_07.png','adulto',DATE '2024-01-18');
INSERT INTO PERFILES VALUES (12,6,'Familia','av_08.png','adulto',DATE '2024-01-18');
INSERT INTO PERFILES VALUES (13,7,'Natalia','av_09.png','adulto',DATE '2024-03-10');
INSERT INTO PERFILES VALUES (14,7,'Series','av_10.png','adulto',DATE '2024-03-10');
INSERT INTO PERFILES VALUES (15,8,'Daniel','av_11.png','adulto',DATE '2023-09-01');
INSERT INTO PERFILES VALUES (16,8,'Cine','av_12.png','adulto',DATE '2023-09-01');
INSERT INTO PERFILES VALUES (17,8,'Docs','av_13.png','adulto',DATE '2023-09-01');
INSERT INTO PERFILES VALUES (18,8,'Peques2','av_kids05.png','infantil',DATE '2023-10-01');
INSERT INTO PERFILES VALUES (19,9,'Carolina','av_14.png','adulto',DATE '2023-10-15');
INSERT INTO PERFILES VALUES (20,9,'Películas','av_15.png','adulto',DATE '2023-10-15');
INSERT INTO PERFILES VALUES (21,9,'Peques3','av_kids06.png','infantil',DATE '2024-01-01');
INSERT INTO PERFILES VALUES (22,10,'Esteban','av_16.png','adulto',DATE '2024-02-01');
INSERT INTO PERFILES VALUES (23,10,'Maratones','av_17.png','adulto',DATE '2024-02-01');

-- Medellín
INSERT INTO PERFILES VALUES (24,11,'Mariana','av_18.png','adulto',DATE '2024-01-20');
INSERT INTO PERFILES VALUES (25,11,'Kids','av_kids07.png','infantil',DATE '2024-01-20');
INSERT INTO PERFILES VALUES (26,12,'Camilo','av_19.png','adulto',DATE '2024-02-28');
INSERT INTO PERFILES VALUES (27,13,'Tatiana','av_20.png','adulto',DATE '2024-04-01');
INSERT INTO PERFILES VALUES (28,13,'Pequeños','av_kids08.png','infantil',DATE '2024-04-01');
INSERT INTO PERFILES VALUES (29,14,'Tomás','av_21.png','adulto',DATE '2023-08-15');
INSERT INTO PERFILES VALUES (30,14,'Noche','av_22.png','adulto',DATE '2023-08-15');
INSERT INTO PERFILES VALUES (31,14,'Mañana','av_23.png','adulto',DATE '2024-01-01');
INSERT INTO PERFILES VALUES (32,15,'Isabella','av_24.png','adulto',DATE '2023-07-01');
INSERT INTO PERFILES VALUES (33,15,'Playlist','av_25.png','adulto',DATE '2023-07-01');
INSERT INTO PERFILES VALUES (34,16,'Mauricio','av_26.png','adulto',DATE '2024-01-05');
INSERT INTO PERFILES VALUES (35,16,'Familia','av_27.png','adulto',DATE '2024-01-05');
INSERT INTO PERFILES VALUES (36,17,'Alejandra','av_28.png','adulto',DATE '2024-03-20');
INSERT INTO PERFILES VALUES (37,17,'Madrugada','av_29.png','adulto',DATE '2024-03-20');
INSERT INTO PERFILES VALUES (38,18,'Santiago','av_30.png','adulto',DATE '2023-06-01');
INSERT INTO PERFILES VALUES (39,18,'Deportes','av_31.png','adulto',DATE '2023-06-01');
INSERT INTO PERFILES VALUES (40,18,'Arte','av_32.png','adulto',DATE '2023-06-01');
INSERT INTO PERFILES VALUES (41,18,'SantiagoJr','av_kids09.png','infantil',DATE '2023-07-01');
INSERT INTO PERFILES VALUES (42,18,'Valeria','av_kids10.png','infantil',DATE '2023-08-01');
INSERT INTO PERFILES VALUES (43,19,'Valentina','av_33.png','adulto',DATE '2023-09-20');
INSERT INTO PERFILES VALUES (44,19,'Series','av_34.png','adulto',DATE '2023-09-20');
INSERT INTO PERFILES VALUES (45,19,'Música','av_35.png','adulto',DATE '2024-01-01');
INSERT INTO PERFILES VALUES (46,20,'Rodrigo','av_36.png','adulto',DATE '2024-01-10');
INSERT INTO PERFILES VALUES (47,20,'Trabajo','av_37.png','adulto',DATE '2024-01-10');
INSERT INTO PERFILES VALUES (48,20,'Casa','av_38.png','adulto',DATE '2024-01-10');

-- Cali y Armenia
INSERT INTO PERFILES VALUES (49,21,'Luisa','av_39.png','adulto',DATE '2024-02-10');
INSERT INTO PERFILES VALUES (50,21,'LuisaJr','av_kids11.png','infantil',DATE '2024-02-10');
INSERT INTO PERFILES VALUES (51,22,'Jorge','av_40.png','adulto',DATE '2024-03-05');
INSERT INTO PERFILES VALUES (52,23,'Gabriela','av_41.png','adulto',DATE '2023-12-01');
INSERT INTO PERFILES VALUES (53,23,'GabiJr','av_kids12.png','infantil',DATE '2024-01-01');
INSERT INTO PERFILES VALUES (54,24,'Hernán','av_42.png','adulto',DATE '2024-01-25');
INSERT INTO PERFILES VALUES (55,24,'Docs','av_43.png','adulto',DATE '2024-01-25');

COMMIT;
DBMS_OUTPUT.PUT_LINE('Sección 4 completada: 55 perfiles.');

-- ============================================================================
-- SECCIÓN 5: CONTENIDO (40 registros)
-- ============================================================================
-- Columnas: id_contenido, titulo, anio_lanzamiento, duracion_min, sinopsis,
--           clasificacion_edad, fecha_agregado, es_original, popularidad,
--           id_categoria, id_empleado_resp

-- PELÍCULAS (10 — cat=1)
INSERT INTO CONTENIDO VALUES (1,'El Cóndor de los Andes',2022,118,'Un piloto descubre una conspiración al cruzar la cordillera.','+13',DATE '2022-08-15','N',0,1,4);
INSERT INTO CONTENIDO VALUES (2,'Bogotá 2050',2023,125,'Futuro distópico donde la IA gobierna la capital colombiana.','+13',DATE '2023-03-20','S',0,1,5);
INSERT INTO CONTENIDO VALUES (3,'La Cumbia del Diablo',2021,98,'Un músico vallenato vende su alma por la fama eterna.','+16',DATE '2021-11-01','N',0,1,4);
INSERT INTO CONTENIDO VALUES (4,'Amar en Medellín',2023,112,'Historia de amor entre dos familias rivales en Laureles.','+13',DATE '2023-07-10','S',0,1,6);
INSERT INTO CONTENIDO VALUES (5,'Selva Adentro',2022,107,'Equipo de rescate busca científicos perdidos en el Amazonas.','+13',DATE '2022-04-05','N',0,1,5);
INSERT INTO CONTENIDO VALUES (6,'El Último Vallenato',2024,134,'El último juglar tradicional del Caribe colombiano.','TP',DATE '2024-01-20','S',0,1,4);
INSERT INTO CONTENIDO VALUES (7,'Héroes de Cartagena',2023,110,'Bomberos de Cartagena enfrentan el mayor incendio.','+13',DATE '2023-09-15','N',0,1,7);
INSERT INTO CONTENIDO VALUES (8,'Pequeños Detectives',2024,85,'Tres niños resuelven el misterio del perro desaparecido.','TP',DATE '2024-02-14','S',0,1,6);
INSERT INTO CONTENIDO VALUES (9,'La Fórmula',2022,102,'Química descubre que su laboratorio fabrica algo ilegal.','+16',DATE '2022-06-30','N',0,1,8);
INSERT INTO CONTENIDO VALUES (10,'Universo Quindío',2024,121,'Jóvenes astrónomos armenios detectan señal extraterrestre.','+13',DATE '2024-03-01','S',0,1,5);

-- SERIES (12 — cat=2)
INSERT INTO CONTENIDO VALUES (11,'Café Amargo',2022,45,'Drama familiar en hacienda cafetera del Quindío. Original.','+13',DATE '2022-09-01','S',0,2,4);
INSERT INTO CONTENIDO VALUES (12,'Los Detectives',2023,50,'Dos detectives bogotanos con métodos opuestos.','+16',DATE '2023-02-15','N',0,2,5);
INSERT INTO CONTENIDO VALUES (13,'Familia Caribe',2021,30,'Comedia de familia caribeña que se muda a Bogotá.','TP',DATE '2021-06-01','S',0,2,6);
INSERT INTO CONTENIDO VALUES (14,'Código Rojo',2024,55,'Médicos de urgencias en Bogotá ante una pandemia.','+16',DATE '2024-01-10','N',0,2,7);
INSERT INTO CONTENIDO VALUES (15,'Amor en Bogotá',2023,45,'Romance en la era digital entre dos desconocidos.','+13',DATE '2023-05-20','S',0,2,4);
INSERT INTO CONTENIDO VALUES (16,'Tech Colombia',2024,50,'Start-up bogotana revoluciona la IA en Latinoamérica.','+13',DATE '2024-02-28','S',0,2,8);
INSERT INTO CONTENIDO VALUES (17,'El Restaurante',2022,40,'Drama culinario en restaurante gourmet de Cartagena.','+13',DATE '2022-11-10','N',0,2,5);
INSERT INTO CONTENIDO VALUES (18,'Misterios Andinos',2023,45,'Periodista investiga desapariciones en los Andes.','+16',DATE '2023-08-01','N',0,2,6);
INSERT INTO CONTENIDO VALUES (19,'Aventuras Escolares',2024,25,'Niños de primaria viven aventuras mágicas.','TP',DATE '2024-03-15','S',0,2,7);
INSERT INTO CONTENIDO VALUES (20,'La Selección',2022,50,'Drama tras bambalinas de la selección colombiana.','+13',DATE '2022-07-20','N',0,2,4);
INSERT INTO CONTENIDO VALUES (21,'Salsa y Amor',2023,40,'Bailarina caleña busca triunfar internacionalmente.','TP',DATE '2023-10-05','S',0,2,8);
INSERT INTO CONTENIDO VALUES (22,'El Político',2024,55,'Vida privada y pública de un candidato presidencial.','+16',DATE '2024-04-01','N',0,2,5);

-- DOCUMENTALES (8 — cat=3)
INSERT INTO CONTENIDO VALUES (23,'Colombia Natural',2023,95,'Expedición por los 6 ecosistemas únicos de Colombia.','TP',DATE '2023-01-15','S',0,3,4);
INSERT INTO CONTENIDO VALUES (24,'Paz y Memoria',2022,110,'Testimonios de comunidades en el conflicto armado.','+13',DATE '2022-05-10','N',0,3,6);
INSERT INTO CONTENIDO VALUES (25,'Gastronomía Colombiana',2024,85,'Viaje por los 32 departamentos del país.','TP',DATE '2024-01-05','S',0,3,5);
INSERT INTO CONTENIDO VALUES (26,'Los Cafeteros',2021,90,'La vida de las familias cafeteras del Eje Cafetero.','TP',DATE '2021-09-20','N',0,3,7);
INSERT INTO CONTENIDO VALUES (27,'Mares de Colombia',2023,88,'Los océanos colombianos vistos desde adentro.','TP',DATE '2023-06-15','S',0,3,4);
INSERT INTO CONTENIDO VALUES (28,'Ciudad Eterna: Bogotá',2022,78,'Historia de 500 años de la capital colombiana.','TP',DATE '2022-08-28','N',0,3,8);
INSERT INTO CONTENIDO VALUES (29,'Biodiversidad Amazónica',2024,92,'La selva amazónica y sus especies en peligro.','TP',DATE '2024-02-10','S',0,3,5);
INSERT INTO CONTENIDO VALUES (30,'Historia Precolombina',2023,105,'Los grandes imperios indígenas del territorio colombiano.','TP',DATE '2023-04-01','N',0,3,6);

-- MÚSICA (5 — cat=4)
INSERT INTO CONTENIDO VALUES (31,'Sinfónica de Bogotá Vol.1',2024,75,'Concierto de la Filarmónica en el Teatro Mayor.','TP',DATE '2024-01-30','S',0,4,7);
INSERT INTO CONTENIDO VALUES (32,'Vallenato Clásico',2023,80,'Grandes éxitos del vallenato con voces nuevas.','TP',DATE '2023-11-20','N',0,4,8);
INSERT INTO CONTENIDO VALUES (33,'Rock Colombiano',2024,65,'Bandas emergentes de rock en concierto.','TP',DATE '2024-03-10','N',0,4,4);
INSERT INTO CONTENIDO VALUES (34,'Jazz Caribe',2023,70,'Fusión de jazz y ritmos caribeños en Barranquilla.','TP',DATE '2023-07-25','S',0,4,5);
INSERT INTO CONTENIDO VALUES (35,'Cumbia Moderna',2024,60,'Artistas urbanos reinventan la cumbia colombiana.','TP',DATE '2024-04-05','N',0,4,6);

-- PODCASTS (5 — cat=5)
INSERT INTO CONTENIDO VALUES (36,'Negocios Colombia',2024,45,'Entrevistas con emprendedores exitosos.','TP',DATE '2024-01-08','S',0,5,7);
INSERT INTO CONTENIDO VALUES (37,'Ciencia al Día',2024,35,'Divulgación científica accesible para todos.','TP',DATE '2024-02-01','N',0,5,8);
INSERT INTO CONTENIDO VALUES (38,'Historia Viva',2023,40,'Momentos importantes de la historia colombiana.','TP',DATE '2023-09-01','S',0,5,4);
INSERT INTO CONTENIDO VALUES (39,'Emprendimiento Joven',2024,30,'Jóvenes menores de 30 con empresas exitosas.','TP',DATE '2024-03-20','N',0,5,5);
INSERT INTO CONTENIDO VALUES (40,'Filosofía Popular',2023,38,'Preguntas filosóficas con ejemplos cotidianos.','TP',DATE '2023-10-15','S',0,5,6);

COMMIT;
DBMS_OUTPUT.PUT_LINE('Sección 5 completada: 40 contenidos (10 pelíc, 12 series, 8 docs, 5 música, 5 pods).');

-- ============================================================================
-- SECCIÓN 6: CONTENIDO_GENERO (44 registros — tabla N:M)
-- ============================================================================
INSERT INTO CONTENIDO_GENERO VALUES (1,3);  INSERT INTO CONTENIDO_GENERO VALUES (1,1);
INSERT INTO CONTENIDO_GENERO VALUES (2,6);  INSERT INTO CONTENIDO_GENERO VALUES (2,4);
INSERT INTO CONTENIDO_GENERO VALUES (3,7);  INSERT INTO CONTENIDO_GENERO VALUES (3,9);
INSERT INTO CONTENIDO_GENERO VALUES (4,5);  INSERT INTO CONTENIDO_GENERO VALUES (4,3);
INSERT INTO CONTENIDO_GENERO VALUES (5,1);  INSERT INTO CONTENIDO_GENERO VALUES (5,3);
INSERT INTO CONTENIDO_GENERO VALUES (6,9);  INSERT INTO CONTENIDO_GENERO VALUES (6,3);
INSERT INTO CONTENIDO_GENERO VALUES (7,1);  INSERT INTO CONTENIDO_GENERO VALUES (7,3);
INSERT INTO CONTENIDO_GENERO VALUES (8,8);  INSERT INTO CONTENIDO_GENERO VALUES (8,2);
INSERT INTO CONTENIDO_GENERO VALUES (9,4);  INSERT INTO CONTENIDO_GENERO VALUES (9,10);
INSERT INTO CONTENIDO_GENERO VALUES (10,6); INSERT INTO CONTENIDO_GENERO VALUES (10,4);
INSERT INTO CONTENIDO_GENERO VALUES (11,3);
INSERT INTO CONTENIDO_GENERO VALUES (12,4); INSERT INTO CONTENIDO_GENERO VALUES (12,10);
INSERT INTO CONTENIDO_GENERO VALUES (13,2); INSERT INTO CONTENIDO_GENERO VALUES (13,8);
INSERT INTO CONTENIDO_GENERO VALUES (14,1); INSERT INTO CONTENIDO_GENERO VALUES (14,3);
INSERT INTO CONTENIDO_GENERO VALUES (15,5); INSERT INTO CONTENIDO_GENERO VALUES (15,3);
INSERT INTO CONTENIDO_GENERO VALUES (16,6); INSERT INTO CONTENIDO_GENERO VALUES (16,4);
INSERT INTO CONTENIDO_GENERO VALUES (17,3); INSERT INTO CONTENIDO_GENERO VALUES (17,2);
INSERT INTO CONTENIDO_GENERO VALUES (18,7); INSERT INTO CONTENIDO_GENERO VALUES (18,4);
INSERT INTO CONTENIDO_GENERO VALUES (19,8); INSERT INTO CONTENIDO_GENERO VALUES (19,2);
INSERT INTO CONTENIDO_GENERO VALUES (20,3); INSERT INTO CONTENIDO_GENERO VALUES (20,1);
INSERT INTO CONTENIDO_GENERO VALUES (21,9); INSERT INTO CONTENIDO_GENERO VALUES (21,5);
INSERT INTO CONTENIDO_GENERO VALUES (22,3); INSERT INTO CONTENIDO_GENERO VALUES (22,4);
INSERT INTO CONTENIDO_GENERO VALUES (23,3); INSERT INTO CONTENIDO_GENERO VALUES (25,3);
INSERT INTO CONTENIDO_GENERO VALUES (31,9); INSERT INTO CONTENIDO_GENERO VALUES (32,9);
INSERT INTO CONTENIDO_GENERO VALUES (34,9); INSERT INTO CONTENIDO_GENERO VALUES (35,9);

COMMIT;

-- ============================================================================
-- SECCIÓN 7: CONTENIDO_RELACIONADO (relación reflexiva N:M)
-- ============================================================================
INSERT INTO CONTENIDO_RELACIONADO VALUES (2,10,'precuela','Bogotá 2050 es precuela de Universo Quindío');
INSERT INTO CONTENIDO_RELACIONADO VALUES (4,15,'spin-off','Amar en Medellín originó la serie Amor en Bogotá');
INSERT INTO CONTENIDO_RELACIONADO VALUES (9,12,'relacionado','La Fórmula inspiró la serie Los Detectives');
INSERT INTO CONTENIDO_RELACIONADO VALUES (23,29,'version_extendida','Biodiversidad Amazónica amplía Colombia Natural');
COMMIT;

-- ============================================================================
-- SECCIÓN 8: TEMPORADAS (15 registros)
-- ============================================================================
-- Columnas: id_temporada, id_contenido, numero_temporada, titulo_temporada, anio_temporada
INSERT INTO TEMPORADAS VALUES (1,11,1,'El Origen del Café',2022);
INSERT INTO TEMPORADAS VALUES (2,11,2,'La Cosecha Amarga',2023);
INSERT INTO TEMPORADAS VALUES (3,11,3,'El Legado',2024);
INSERT INTO TEMPORADAS VALUES (4,12,1,'Primera Investigación',2023);
INSERT INTO TEMPORADAS VALUES (5,12,2,'El Caso Imposible',2024);
INSERT INTO TEMPORADAS VALUES (6,13,1,'Llegando a Bogotá',2021);
INSERT INTO TEMPORADAS VALUES (7,13,2,'Adaptándose',2022);
INSERT INTO TEMPORADAS VALUES (8,13,3,'Ya Somos Bogotanos',2023);
INSERT INTO TEMPORADAS VALUES (9,15,1,'El Primer Mensaje',2023);
INSERT INTO TEMPORADAS VALUES (10,15,2,'El Primer Encuentro',2024);
INSERT INTO TEMPORADAS VALUES (11,36,1,'Emprendedores 2024',2024);
INSERT INTO TEMPORADAS VALUES (12,36,2,'Casos de Éxito',2024);
INSERT INTO TEMPORADAS VALUES (13,37,1,'Ciencia Básica',2024);
INSERT INTO TEMPORADAS VALUES (14,37,2,'Fronteras del Conocimiento',2024);
INSERT INTO TEMPORADAS VALUES (15,38,1,'Colombia Colonial',2023);
COMMIT;

-- ============================================================================
-- SECCIÓN 9: EPISODIOS (50 registros)
-- ============================================================================
-- Columnas: id_episodio, id_temporada, numero_episodio, titulo_episodio, duracion_min, sinopsis_ep

-- Café Amargo T1 (temp=1): eps 1-6
INSERT INTO EPISODIOS VALUES (1,1,1,'Semillas en la Tierra',48,'El patriarca planta la primera mata de café.');
INSERT INTO EPISODIOS VALUES (2,1,2,'Las Primeras Lluvias',46,'La familia enfrenta una sequía inesperada.');
INSERT INTO EPISODIOS VALUES (3,1,3,'El Vecino Extraño',50,'Un forastero llega con secretos.');
INSERT INTO EPISODIOS VALUES (4,1,4,'La Primera Cosecha',44,'Llega el momento más esperado del año.');
INSERT INTO EPISODIOS VALUES (5,1,5,'Amores Prohibidos',47,'Jóvenes de familias rivales se enamoran.');
INSERT INTO EPISODIOS VALUES (6,1,6,'El Final del Verano',52,'La hacienda enfrenta su primera crisis.');
-- Café Amargo T2 (temp=2): eps 7-12
INSERT INTO EPISODIOS VALUES (7,2,1,'Nuevos Horizontes',45,'La segunda generación toma el control.');
INSERT INTO EPISODIOS VALUES (8,2,2,'La Amenaza',48,'Empresa extranjera quiere comprar la hacienda.');
INSERT INTO EPISODIOS VALUES (9,2,3,'Resistencia',50,'La familia se organiza para luchar.');
INSERT INTO EPISODIOS VALUES (10,2,4,'Traición',46,'Alguien vende los secretos de la familia.');
INSERT INTO EPISODIOS VALUES (11,2,5,'El Gran Error',49,'Una decisión lo cambia todo.');
INSERT INTO EPISODIOS VALUES (12,2,6,'Redención',53,'El patriarca busca reparar el daño.');
-- Café Amargo T3 (temp=3): eps 13-16
INSERT INTO EPISODIOS VALUES (13,3,1,'El Legado',45,'Tercera generación hereda el café.');
INSERT INTO EPISODIOS VALUES (14,3,2,'Modernización',48,'Tecnología vs tradición.');
INSERT INTO EPISODIOS VALUES (15,3,3,'La Última Cosecha',50,'La cosecha más importante.');
INSERT INTO EPISODIOS VALUES (16,3,4,'Raíces',55,'El origen de la familia se revela.');
-- Los Detectives T1 (temp=4): eps 17-21
INSERT INTO EPISODIOS VALUES (17,4,1,'El Caso del Banco',52,'Robo sin huellas en el Banco de la República.');
INSERT INTO EPISODIOS VALUES (18,4,2,'Pistas Falsas',50,'Los detectives siguen una pista errónea.');
INSERT INTO EPISODIOS VALUES (19,4,3,'El Testigo',48,'Un testigo clave desaparece.');
INSERT INTO EPISODIOS VALUES (20,4,4,'En la Trampa',54,'Los detectives caen en emboscada.');
INSERT INTO EPISODIOS VALUES (21,4,5,'La Verdad',56,'El criminal más inesperado revelado.');
-- Los Detectives T2 (temp=5): eps 22-26
INSERT INTO EPISODIOS VALUES (22,5,1,'Regreso',50,'Los detectives vuelven con caso imposible.');
INSERT INTO EPISODIOS VALUES (23,5,2,'El Archivo',48,'Un archivo secreto contiene la clave.');
INSERT INTO EPISODIOS VALUES (24,5,3,'Alianzas',52,'Buscan aliados inesperados.');
INSERT INTO EPISODIOS VALUES (25,5,4,'Confrontación',55,'El enfrentamiento final se acerca.');
INSERT INTO EPISODIOS VALUES (26,5,5,'Justicia',58,'El caso más difícil llega a su fin.');
-- Familia Caribe T1 (temp=6): eps 27-31
INSERT INTO EPISODIOS VALUES (27,6,1,'El Traslado',30,'La familia sale de Barranquilla.');
INSERT INTO EPISODIOS VALUES (28,6,2,'El Frío',28,'Primer choque con el clima bogotano.');
INSERT INTO EPISODIOS VALUES (29,6,3,'Los Vecinos',32,'Los vecinos no entienden el acento.');
INSERT INTO EPISODIOS VALUES (30,6,4,'El Colegio',29,'Los niños van al colegio bogotano.');
INSERT INTO EPISODIOS VALUES (31,6,5,'La Nostalgia',31,'Todos extrañan el calor del Caribe.');
-- Familia Caribe T2 (temp=7): eps 32-35
INSERT INTO EPISODIOS VALUES (32,7,1,'Ya Aprendimos',30,'La familia domina el transporte bogotano.');
INSERT INTO EPISODIOS VALUES (33,7,2,'El Trabajo',28,'El papá consigue trabajo.');
INSERT INTO EPISODIOS VALUES (34,7,3,'Amigos Nuevos',32,'Los hijos hacen amigos bogotanos.');
INSERT INTO EPISODIOS VALUES (35,7,4,'La Visita',35,'Los abuelos llegan de Barranquilla.');
-- Familia Caribe T3 (temp=8): eps 36-38
INSERT INTO EPISODIOS VALUES (36,8,1,'Primeras Navidades',30,'Primera navidad en Bogotá.');
INSERT INTO EPISODIOS VALUES (37,8,2,'El Regreso',32,'¿Regresar al Caribe o quedarse?');
INSERT INTO EPISODIOS VALUES (38,8,3,'Raíces y Alas',34,'Son bogotanos y caribeños.');
-- Amor en Bogotá T1 (temp=9): eps 39-43
INSERT INTO EPISODIOS VALUES (39,9,1,'El Perfil',45,'Dos extraños se cruzan en una app.');
INSERT INTO EPISODIOS VALUES (40,9,2,'El Primer Chat',44,'Una conversación que dura toda la noche.');
INSERT INTO EPISODIOS VALUES (41,9,3,'La Coincidencia',46,'Se descubren viviendo a dos cuadras.');
INSERT INTO EPISODIOS VALUES (42,9,4,'El Primer Café',48,'La primera cita presencial.');
INSERT INTO EPISODIOS VALUES (43,9,5,'Complicaciones',47,'Sus diferencias salen a la luz.');
-- Amor en Bogotá T2 (temp=10): eps 44-47
INSERT INTO EPISODIOS VALUES (44,10,1,'El Reencuentro',45,'Después de 3 meses se vuelven a ver.');
INSERT INTO EPISODIOS VALUES (45,10,2,'La Verdad',46,'Cada uno revela su mayor secreto.');
INSERT INTO EPISODIOS VALUES (46,10,3,'La Decisión',48,'¿Seguir o terminar?');
INSERT INTO EPISODIOS VALUES (47,10,4,'Para Siempre',50,'El final que nadie esperaba.');
-- Podcasts: Negocios T1, Ciencia T1, Historia T1: eps 48-50
INSERT INTO EPISODIOS VALUES (48,11,1,'Cómo Empezar de Cero',45,'Tres emprendedores cuentan sus inicios.');
INSERT INTO EPISODIOS VALUES (49,13,1,'El ADN Explicado',35,'Qué es el ADN y cómo afecta tu vida.');
INSERT INTO EPISODIOS VALUES (50,15,1,'La Conquista Española',40,'Los primeros 50 años de Colombia colonial.');

COMMIT;
DBMS_OUTPUT.PUT_LINE('Sección 8-9 completada: 15 temporadas, 50 episodios.');

-- ============================================================================
-- SECCIÓN 10: PAGOS (80 registros con PL/SQL)
-- ============================================================================
DECLARE
    v_metodos  SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST('TC','TD','PSE','Nequi','Daviplata');
    v_pago_id  NUMBER := 1;
    v_estado   VARCHAR2(15);
    v_fecha    DATE;
    v_precio   NUMBER;
BEGIN
    FOR u IN (SELECT u.id_usuario, u.id_plan, p.precio_mensual
              FROM USUARIOS u JOIN PLANES p ON u.id_plan = p.id_plan
              ORDER BY u.id_usuario)
    LOOP
        FOR mes IN 1..CASE WHEN MOD(u.id_usuario,3)=0 THEN 2 ELSE 3 END LOOP

            v_fecha := ADD_MONTHS(DATE '2026-04-10', -mes);

            IF u.id_usuario IN (3,13,22) AND mes = 1 THEN
                v_estado := 'FALLIDO';
            ELSIF MOD(u.id_usuario + mes, 10) = 0 THEN
                v_estado := 'REEMBOLSADO';
            ELSIF MOD(u.id_usuario + mes, 7) = 0 THEN
                v_estado := 'FALLIDO';
            ELSIF MOD(u.id_usuario + mes, 15) = 0 THEN
                v_estado := 'PENDIENTE';
            ELSE
                v_estado := 'EXITOSO';
            END IF;

            INSERT INTO PAGOS VALUES (
                v_pago_id,
                u.id_usuario,
                v_fecha,
                u.precio_mensual,
                v_metodos(MOD(u.id_usuario + mes, 5) + 1),
                v_estado,
                EXTRACT(MONTH FROM v_fecha),
                EXTRACT(YEAR  FROM v_fecha)
            );
            v_pago_id := v_pago_id + 1;
        END LOOP;
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Pagos insertados: ' || (v_pago_id - 1));
END;
/

-- ============================================================================
-- SECCIÓN 11: REPRODUCCIONES (200 registros con PL/SQL)
-- ============================================================================
-- Distribuidas: ~60 en 2024, ~80 en 2025, ~60 en 2026
-- Demuestra el particionamiento de la tabla por fecha

DECLARE
    v_dispositivos SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST('celular','tablet','TV','computador');
    v_perfiles     SYS.ODCINNUMBERLIST  := SYS.ODCINNUMBERLIST(
                       1,2,3,6,8,9,11,13,14,15,16,17,19,20,22,23,
                       24,26,29,30,31,32,33,34,36,38,39,40,43,44,
                       45,46,47,49,52,54,55,8,9,15,16,32,38,43,1,15,32);
    v_id_rep   NUMBER := 1;
    v_perf     NUMBER;
    v_cont     NUMBER;
    v_ep       NUMBER;
    v_fecha    TIMESTAMP;
    v_fin      TIMESTAMP;
    v_disp     VARCHAR2(15);
    v_porc     NUMBER;
    v_dur      NUMBER;
BEGIN
    FOR i IN 1..200 LOOP
        v_perf := v_perfiles(MOD(i-1, v_perfiles.COUNT) + 1);
        v_cont := MOD(i * 7 + 3, 40) + 1;
        v_disp := v_dispositivos(MOD(i, 4) + 1);
        v_porc := CASE MOD(i, 5)
                    WHEN 0 THEN 100
                    WHEN 1 THEN MOD(i * 3, 20) + 80
                    WHEN 2 THEN MOD(i * 3, 30) + 50
                    WHEN 3 THEN MOD(i * 3, 30) + 20
                    ELSE        MOD(i * 3, 20) + 1
                  END;

        -- Distribuir en 3 años para demostrar particionamiento
        v_fecha := CASE
            WHEN i <= 60  THEN TIMESTAMP '2024-01-15 08:00:00' + NUMTODSINTERVAL(MOD(i*73,330), 'DAY')
            WHEN i <= 140 THEN TIMESTAMP '2025-01-10 09:00:00' + NUMTODSINTERVAL(MOD(i*59,350), 'DAY')
            ELSE               TIMESTAMP '2026-01-05 10:00:00' + NUMTODSINTERVAL(MOD(i*41,100), 'DAY')
        END;

        SELECT duracion_min INTO v_dur FROM CONTENIDO WHERE id_contenido = v_cont;
        v_fin := v_fecha + NUMTODSINTERVAL(ROUND(v_dur * v_porc / 100.0), 'MINUTE');

        -- Episodio para series y podcasts con episodios
        v_ep := NULL;
        IF    v_cont = 11 THEN v_ep := MOD(i*3,16) + 1;
        ELSIF v_cont = 12 THEN v_ep := MOD(i*3,10) + 17;
        ELSIF v_cont = 13 THEN v_ep := MOD(i*3,12) + 27;
        ELSIF v_cont = 15 THEN v_ep := MOD(i*3, 9) + 39;
        ELSIF v_cont = 36 THEN v_ep := 48;
        ELSIF v_cont = 37 THEN v_ep := 49;
        ELSIF v_cont = 38 THEN v_ep := 50;
        END IF;

        INSERT INTO REPRODUCCIONES VALUES (
            v_id_rep, v_perf, v_cont, v_ep,
            v_fecha, v_fin, v_disp, v_porc
        );
        v_id_rep := v_id_rep + 1;
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Reproducciones insertadas: ' || (v_id_rep - 1));
END;
/

-- ============================================================================
-- SECCIÓN 12: CALIFICACIONES (60 registros con PL/SQL)
-- ============================================================================
-- FIX: Se usa GROUP BY para garantizar pares únicos (id_perfil, id_contenido)
-- Solo para contenido visto >= 50% (regla de negocio RN-05)

DECLARE
    v_cal_id  NUMBER := 1;
    v_estrellas NUMBER;
    v_resenas SYS.ODCIVARCHAR2LIST := SYS.ODCIVARCHAR2LIST(
        'Excelente producción colombiana, muy recomendada.',
        'Buena historia pero el final me decepcionó un poco.',
        'Increíble trabajo del elenco, me encantó cada episodio.',
        'Entretenida pero predecible en algunos momentos.',
        'Una joya del cine colombiano, hay que verla.',
        'Me pareció regular, esperaba más de esta producción.',
        'Perfecta para ver en familia los domingos.',
        'La fotografía es espectacular, muy bien hecha.',
        NULL,
        NULL
    );
BEGIN
    -- GROUP BY garantiza pares únicos (evita ORA-00001 en UNIQUE constraint)
    FOR r IN (
        SELECT id_perfil, id_contenido,
               ROW_NUMBER() OVER (ORDER BY id_perfil, id_contenido) rn
        FROM (
            SELECT DISTINCT id_perfil, id_contenido
            FROM REPRODUCCIONES
            WHERE porcentaje_avance >= 50
              AND id_perfil NOT IN (4,5,27,28,51)
        )
        FETCH FIRST 60 ROWS ONLY
    ) LOOP
        v_estrellas := MOD(r.rn, 5) + 1;
        INSERT INTO CALIFICACIONES VALUES (
            v_cal_id,
            r.id_perfil,
            r.id_contenido,
            v_estrellas,
            v_resenas(MOD(r.rn - 1, v_resenas.COUNT) + 1),
            SYSDATE - MOD(r.rn * 7, 90)
        );
        v_cal_id := v_cal_id + 1;
    END LOOP;
    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Calificaciones insertadas: ' || (v_cal_id - 1));
END;
/

-- ============================================================================
-- SECCIÓN 13: FAVORITOS (40 registros — tabla N:M)
-- ============================================================================
INSERT INTO FAVORITOS VALUES (1,11,DATE '2024-02-01');  INSERT INTO FAVORITOS VALUES (1,2,DATE '2024-03-10');
INSERT INTO FAVORITOS VALUES (3,4,DATE '2024-03-20');   INSERT INTO FAVORITOS VALUES (3,15,DATE '2024-04-01');
INSERT INTO FAVORITOS VALUES (6,1,DATE '2024-01-25');   INSERT INTO FAVORITOS VALUES (6,23,DATE '2024-02-14');
INSERT INTO FAVORITOS VALUES (8,11,DATE '2023-10-01');  INSERT INTO FAVORITOS VALUES (8,2,DATE '2023-11-15');
INSERT INTO FAVORITOS VALUES (9,15,DATE '2023-12-01');  INSERT INTO FAVORITOS VALUES (9,13,DATE '2024-01-20');
INSERT INTO FAVORITOS VALUES (11,5,DATE '2024-02-28');  INSERT INTO FAVORITOS VALUES (13,3,DATE '2024-04-10');
INSERT INTO FAVORITOS VALUES (14,11,DATE '2023-09-01'); INSERT INTO FAVORITOS VALUES (15,34,DATE '2023-08-15');
INSERT INTO FAVORITOS VALUES (16,11,DATE '2024-02-01'); INSERT INTO FAVORITOS VALUES (19,21,DATE '2023-10-20');
INSERT INTO FAVORITOS VALUES (20,12,DATE '2024-02-15'); INSERT INTO FAVORITOS VALUES (22,8,DATE '2024-02-10');
INSERT INTO FAVORITOS VALUES (24,25,DATE '2024-01-30'); INSERT INTO FAVORITOS VALUES (26,7,DATE '2023-12-10');
INSERT INTO FAVORITOS VALUES (29,11,DATE '2023-09-15'); INSERT INTO FAVORITOS VALUES (30,20,DATE '2024-01-15');
INSERT INTO FAVORITOS VALUES (32,1,DATE '2023-07-20');  INSERT INTO FAVORITOS VALUES (33,13,DATE '2023-08-01');
INSERT INTO FAVORITOS VALUES (38,11,DATE '2023-07-01'); INSERT INTO FAVORITOS VALUES (39,2,DATE '2023-08-10');
INSERT INTO FAVORITOS VALUES (43,15,DATE '2023-10-01'); INSERT INTO FAVORITOS VALUES (44,11,DATE '2023-11-01');
INSERT INTO FAVORITOS VALUES (46,12,DATE '2024-01-20'); INSERT INTO FAVORITOS VALUES (47,9,DATE '2024-02-01');
INSERT INTO FAVORITOS VALUES (49,21,DATE '2024-02-15'); INSERT INTO FAVORITOS VALUES (52,23,DATE '2023-12-20');
INSERT INTO FAVORITOS VALUES (54,1,DATE '2024-02-01');  INSERT INTO FAVORITOS VALUES (55,27,DATE '2024-02-20');
INSERT INTO FAVORITOS VALUES (1,25,DATE '2024-04-10');  INSERT INTO FAVORITOS VALUES (8,25,DATE '2024-03-01');
INSERT INTO FAVORITOS VALUES (15,11,DATE '2023-07-15'); INSERT INTO FAVORITOS VALUES (32,15,DATE '2023-09-01');
INSERT INTO FAVORITOS VALUES (38,13,DATE '2023-09-15'); INSERT INTO FAVORITOS VALUES (43,21,DATE '2024-01-01');
COMMIT;

-- ============================================================================
-- SECCIÓN 14: REPORTES (6 registros)
-- ============================================================================
-- Moderadores que resuelven: usuarios 5, 15, 25 (es_moderador='S')
INSERT INTO REPORTES VALUES (1,4,3,'Escenas de violencia gráfica excesiva',DATE '2025-03-15','RESUELTO',5,DATE '2025-03-18','Clasificación +16 es correcta y ya está aplicada.');
INSERT INTO REPORTES VALUES (2,7,18,'Contenido de terror sin aviso suficiente',DATE '2025-05-20','RESUELTO',15,DATE '2025-05-22','Correcto: clasificación +16. Mensaje enviado al usuario.');
INSERT INTO REPORTES VALUES (3,12,22,'Lenguaje inapropiado sin clasificación adecuada',DATE '2025-08-10','RESUELTO',25,DATE '2025-08-12','Se actualizó clasificación a +16. Reporte válido.');
INSERT INTO REPORTES VALUES (4,21,14,'Escenas de emergencia muy perturbadoras',DATE '2026-01-05','EN_REVISION',NULL,NULL,NULL);
INSERT INTO REPORTES VALUES (5,6,9,'Contenido engañoso en la sinopsis',DATE '2026-02-20','PENDIENTE',NULL,NULL,NULL);
INSERT INTO REPORTES VALUES (6,29,22,'Información política sesgada sin contexto',DATE '2026-03-10','PENDIENTE',NULL,NULL,NULL);
COMMIT;
DBMS_OUTPUT.PUT_LINE('Sección 13-14 completada: Favoritos y Reportes.');

-- ============================================================================
-- SECCIÓN 15: RESETEAR SECUENCIAS IDENTITY
-- ============================================================================
-- START WITH LIMIT VALUE sincroniza la secuencia al máximo valor actual + 1
-- así los próximos INSERTs sin especificar ID no generarán duplicados.

ALTER TABLE PLANES         MODIFY id_plan          GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE CATEGORIAS     MODIFY id_categoria     GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE GENEROS        MODIFY id_genero        GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE DEPARTAMENTOS  MODIFY id_departamento  GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE EMPLEADOS      MODIFY id_empleado      GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE USUARIOS       MODIFY id_usuario       GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE PERFILES       MODIFY id_perfil        GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE CONTENIDO      MODIFY id_contenido     GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE TEMPORADAS     MODIFY id_temporada     GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE EPISODIOS      MODIFY id_episodio      GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE PAGOS          MODIFY id_pago          GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE REPRODUCCIONES MODIFY id_reproduccion  GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE CALIFICACIONES MODIFY id_calificacion  GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE REPORTES       MODIFY id_reporte       GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
DBMS_OUTPUT.PUT_LINE('Secuencias IDENTITY restablecidas.');

-- Actualizar estadísticas para que particiones muestren NUM_ROWS
BEGIN
    DBMS_STATS.GATHER_TABLE_STATS(USER, 'REPRODUCCIONES');
    DBMS_OUTPUT.PUT_LINE('Estadísticas de REPRODUCCIONES actualizadas.');
END;
/

-- ============================================================================
-- SECCIÓN 16: VERIFICACIONES FINALES
-- ============================================================================

-- FIX: ORDER BY 1 en lugar de ORDER BY tabla (ORA-00904 corregido)
SELECT 'PLANES'                AS tabla, COUNT(*) AS registros FROM PLANES               UNION ALL
SELECT 'CATEGORIAS',            COUNT(*) FROM CATEGORIAS          UNION ALL
SELECT 'GENEROS',               COUNT(*) FROM GENEROS              UNION ALL
SELECT 'DEPARTAMENTOS',         COUNT(*) FROM DEPARTAMENTOS        UNION ALL
SELECT 'EMPLEADOS',             COUNT(*) FROM EMPLEADOS            UNION ALL
SELECT 'USUARIOS',              COUNT(*) FROM USUARIOS             UNION ALL
SELECT 'PERFILES',              COUNT(*) FROM PERFILES              UNION ALL
SELECT 'CONTENIDO',             COUNT(*) FROM CONTENIDO            UNION ALL
SELECT 'CONTENIDO_GENERO',      COUNT(*) FROM CONTENIDO_GENERO     UNION ALL
SELECT 'CONTENIDO_RELACIONADO', COUNT(*) FROM CONTENIDO_RELACIONADO UNION ALL
SELECT 'TEMPORADAS',            COUNT(*) FROM TEMPORADAS           UNION ALL
SELECT 'EPISODIOS',             COUNT(*) FROM EPISODIOS             UNION ALL
SELECT 'PAGOS',                 COUNT(*) FROM PAGOS                UNION ALL
SELECT 'REPRODUCCIONES',        COUNT(*) FROM REPRODUCCIONES       UNION ALL
SELECT 'CALIFICACIONES',        COUNT(*) FROM CALIFICACIONES        UNION ALL
SELECT 'FAVORITOS',             COUNT(*) FROM FAVORITOS             UNION ALL
SELECT 'REPORTES',              COUNT(*) FROM REPORTES
ORDER BY 1;

-- Distribución ASIMÉTRICA: usuarios por ciudad y plan
SELECT u.ciudad, p.nombre_plan, COUNT(*) AS usuarios
FROM USUARIOS u JOIN PLANES p ON u.id_plan = p.id_plan
GROUP BY u.ciudad, p.nombre_plan
ORDER BY u.ciudad, p.nombre_plan;

-- Reproducciones por partición (verificar fragmentación)
SELECT partition_name, num_rows
FROM user_tab_partitions
WHERE table_name = 'REPRODUCCIONES'
ORDER BY partition_position;

-- Usuarios con mora (INACTIVOS)
SELECT id_usuario, nombre_usuario, ciudad,
       TRUNC(SYSDATE - fecha_ultimo_pago) AS dias_sin_pago
FROM USUARIOS
WHERE estado_cuenta = 'INACTIVO';

-- ============================================================================
-- FIN DEL SCRIPT — v2 SIN ERRORES
-- ============================================================================
