-- ============================================================================
-- PROYECTO FINAL — BASES DE DATOS II — QuindioFlix
-- Script:  03c_QuindioFlix_Fix_Final.sql
-- Versión: 3 — Sin colecciones PL/SQL (compatibilidad total con Oracle XE)
-- Fixes:
--   ORA-32795 → ALTER BY DEFAULT antes de insertar
--   PLS-00425 → Eliminar TYPE collections, usar CASE directo
-- Ejecutar como quindioflix en QuindioFlixBD
-- ============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;

-- ============================================================================
-- PASO 0: Limpiar tablas vacías
-- ============================================================================
DELETE FROM CALIFICACIONES;
DELETE FROM REPRODUCCIONES;
COMMIT;

-- ============================================================================
-- PASO 0-B: Permitir insertar valores explícitos en columnas IDENTITY
-- (el script v2 las dejó en GENERATED ALWAYS al final)
-- ============================================================================
ALTER TABLE REPRODUCCIONES MODIFY id_reproduccion GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE CALIFICACIONES MODIFY id_calificacion GENERATED BY DEFAULT AS IDENTITY;

-- ============================================================================
-- PASO 1: REPRODUCCIONES (200 registros)
-- Sin colecciones PL/SQL — todo con expresiones CASE y MOD
-- ============================================================================
DECLARE
    v_id_rep  NUMBER := 1;
    v_perf    NUMBER;
    v_cont    NUMBER;
    v_ep      NUMBER;
    v_fecha   TIMESTAMP;
    v_fin     TIMESTAMP;
    v_disp    VARCHAR2(15);
    v_porc    NUMBER;
    v_dur     NUMBER;
BEGIN
    FOR i IN 1..200 LOOP

        -- Seleccionar perfil activo (sin colección — CASE directo)
        -- Lista de 32 perfiles de usuarios ACTIVOS
        v_perf := CASE MOD(i - 1, 32)
            WHEN  0 THEN  1  WHEN  1 THEN  2  WHEN  2 THEN  3
            WHEN  3 THEN  6  WHEN  4 THEN  8  WHEN  5 THEN  9
            WHEN  6 THEN 11  WHEN  7 THEN 13  WHEN  8 THEN 14
            WHEN  9 THEN 15  WHEN 10 THEN 16  WHEN 11 THEN 17
            WHEN 12 THEN 19  WHEN 13 THEN 20  WHEN 14 THEN 22
            WHEN 15 THEN 23  WHEN 16 THEN 24  WHEN 17 THEN 26
            WHEN 18 THEN 29  WHEN 19 THEN 30  WHEN 20 THEN 31
            WHEN 21 THEN 32  WHEN 22 THEN 33  WHEN 23 THEN 34
            WHEN 24 THEN 36  WHEN 25 THEN 38  WHEN 26 THEN 39
            WHEN 27 THEN 40  WHEN 28 THEN 43  WHEN 29 THEN 44
            WHEN 30 THEN 45  WHEN 31 THEN 46  ELSE 1
        END;

        -- Contenido (1-40 distribuido)
        v_cont := MOD(i * 7 + 3, 40) + 1;

        -- Dispositivo (sin colección — CASE directo)
        v_disp := CASE MOD(i, 4)
            WHEN 0 THEN 'celular'
            WHEN 1 THEN 'tablet'
            WHEN 2 THEN 'TV'
            ELSE        'computador'
        END;

        -- Porcentaje variado (100%, 80-99%, 50-79%, 20-49%, 1-20%)
        v_porc := CASE MOD(i, 5)
            WHEN 0 THEN 100
            WHEN 1 THEN MOD(i * 3, 20) + 80
            WHEN 2 THEN MOD(i * 3, 30) + 50
            WHEN 3 THEN MOD(i * 3, 30) + 20
            ELSE        MOD(i * 3, 19) + 1
        END;

        -- Fecha distribuida en 3 particiones (2024, 2025, 2026)
        v_fecha := CASE
            WHEN i <= 60  THEN TIMESTAMP '2024-01-15 08:00:00'
                               + NUMTODSINTERVAL(MOD(i * 73, 330), 'DAY')
            WHEN i <= 140 THEN TIMESTAMP '2025-01-10 09:00:00'
                               + NUMTODSINTERVAL(MOD(i * 59, 350), 'DAY')
            ELSE               TIMESTAMP '2026-01-05 10:00:00'
                               + NUMTODSINTERVAL(MOD(i * 41, 100), 'DAY')
        END;

        -- Duración del contenido para calcular fecha_fin
        SELECT duracion_min INTO v_dur
        FROM CONTENIDO WHERE id_contenido = v_cont;

        v_fin := v_fecha + NUMTODSINTERVAL(ROUND(v_dur * v_porc / 100.0), 'MINUTE');

        -- Episodio (solo para series/podcasts con episodios cargados)
        v_ep := NULL;
        IF    v_cont = 11 THEN v_ep := MOD(i * 3, 16) + 1;   -- Café Amargo: eps 1-16
        ELSIF v_cont = 12 THEN v_ep := MOD(i * 3, 10) + 17;  -- Los Detectives: eps 17-26
        ELSIF v_cont = 13 THEN v_ep := MOD(i * 3, 12) + 27;  -- Familia Caribe: eps 27-38
        ELSIF v_cont = 15 THEN v_ep := MOD(i * 3,  9) + 39;  -- Amor en Bogotá: eps 39-47
        ELSIF v_cont = 36 THEN v_ep := 48;
        ELSIF v_cont = 37 THEN v_ep := 49;
        ELSIF v_cont = 38 THEN v_ep := 50;
        END IF;

        INSERT INTO REPRODUCCIONES
        VALUES (v_id_rep, v_perf, v_cont, v_ep, v_fecha, v_fin, v_disp, v_porc);

        v_id_rep := v_id_rep + 1;
    END LOOP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Reproducciones insertadas: ' || (v_id_rep - 1));
END;
/

-- ============================================================================
-- PASO 2: CALIFICACIONES (hasta 60 registros)
-- Sin TYPE collection — usa CASE para reseñas y ROWNUM para limitar
-- Solo para perfiles que vieron >= 50% (Regla de Negocio RN-05)
-- ============================================================================
DECLARE
    v_cal_id    NUMBER := 1;
    v_estrellas NUMBER;
    v_resena    VARCHAR2(300);
BEGIN
    FOR r IN (
        -- ROWNUM reemplaza ROW_NUMBER() OVER para compatibilidad total
        SELECT ROWNUM AS rn, id_perfil, id_contenido
        FROM (
            SELECT DISTINCT id_perfil, id_contenido
            FROM   REPRODUCCIONES
            WHERE  porcentaje_avance >= 50
              AND  id_perfil NOT IN (4, 5, 27, 28, 51)
        )
        WHERE ROWNUM <= 60
    )
    LOOP
        v_estrellas := MOD(r.rn, 5) + 1;

        -- Reseña según número de registro (sin colección PL/SQL)
        v_resena := CASE MOD(r.rn - 1, 10)
            WHEN 0 THEN 'Excelente producción colombiana, muy recomendada.'
            WHEN 1 THEN 'Buena historia pero el final me decepcionó un poco.'
            WHEN 2 THEN 'Increíble trabajo del elenco, me encantó cada episodio.'
            WHEN 3 THEN 'Entretenida pero predecible en algunos momentos.'
            WHEN 4 THEN 'Una joya del cine colombiano, hay que verla.'
            WHEN 5 THEN 'Me pareció regular, esperaba más de esta producción.'
            WHEN 6 THEN 'Perfecta para ver en familia los domingos.'
            WHEN 7 THEN 'La fotografía es espectacular, muy bien hecha.'
            ELSE NULL  -- algunos sin reseña escrita (solo estrellas)
        END;

        INSERT INTO CALIFICACIONES
        VALUES (
            v_cal_id,
            r.id_perfil,
            r.id_contenido,
            v_estrellas,
            v_resena,
            SYSDATE - MOD(r.rn * 7, 90)
        );

        v_cal_id := v_cal_id + 1;
    END LOOP;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Calificaciones insertadas: ' || (v_cal_id - 1));
END;
/

-- ============================================================================
-- PASO 3: Resetear secuencias y actualizar estadísticas
-- ============================================================================
ALTER TABLE REPRODUCCIONES MODIFY id_reproduccion GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);
ALTER TABLE CALIFICACIONES MODIFY id_calificacion GENERATED ALWAYS AS IDENTITY (START WITH LIMIT VALUE);

BEGIN
    DBMS_STATS.GATHER_TABLE_STATS(USER, 'REPRODUCCIONES');
END;
/

-- ============================================================================
-- VERIFICACIÓN FINAL
-- ============================================================================

-- Conteo de las dos tablas corregidas
SELECT 'REPRODUCCIONES' AS tabla, COUNT(*) AS registros FROM REPRODUCCIONES
UNION ALL
SELECT 'CALIFICACIONES', COUNT(*) FROM CALIFICACIONES;

-- Reproducciones por partición (evidencia del particionamiento)
SELECT partition_name       AS particion,
       num_rows             AS reproducciones,
       tablespace_name      AS tablespace_fisico
FROM   user_tab_partitions
WHERE  table_name = 'REPRODUCCIONES'
ORDER BY partition_position;

-- Reproducciones por año y dispositivo (asimetría de datos)
SELECT EXTRACT(YEAR FROM fecha_inicio) AS anio,
       dispositivo,
       COUNT(*)                        AS total
FROM   REPRODUCCIONES
GROUP  BY EXTRACT(YEAR FROM fecha_inicio), dispositivo
ORDER  BY anio, dispositivo;

-- Calificaciones por estrellas
SELECT estrellas,
       COUNT(*) AS cantidad
FROM   CALIFICACIONES
GROUP  BY estrellas
ORDER  BY estrellas;

-- ============================================================================
-- FIN DEL SCRIPT
-- ============================================================================
